"""Guards for the checked-in setup guide PDF (docs/ApplyOS-setup-guide.pdf).

The PDF is generated by docs/generate_setup_guide.py (reportlab, a local-only
build tool - not a repo dependency). These tests pin the artifact contract
without requiring reportlab or pypdf in CI: when pypdf is missing the
content assertions skip instead of failing.
"""
import unittest
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
GENERATOR = REPO / "docs" / "generate_setup_guide.py"
PDF = REPO / "docs" / "ApplyOS-setup-guide.pdf"

try:
    from pypdf import PdfReader
except ImportError:  # CI runs stdlib-only; content checks skip there.
    PdfReader = None


class SetupGuidePdf(unittest.TestCase):
    def test_generator_and_pdf_exist(self):
        self.assertTrue(GENERATOR.is_file(), "docs/generate_setup_guide.py went missing")
        self.assertTrue(PDF.is_file(), "docs/ApplyOS-setup-guide.pdf went missing - regenerate it")

    def test_source_facts_still_grounded(self):
        # The generator fails loudly when the repo moves under it; this pins
        # that the grounding targets still exist (commands, skills, registry).
        text = GENERATOR.read_text(encoding="utf-8")
        for anchor in (".claude/commands/apply.md", "registry.yaml", "12 portal CLIs"):
            with self.subTest(anchor=anchor):
                self.assertIn(anchor, text)

    @unittest.skipIf(PdfReader is None, "pypdf not installed (local-only check)")
    def test_pdf_has_readable_cover_and_body(self):
        reader = PdfReader(str(PDF))
        self.assertGreaterEqual(len(reader.pages), 5, "guide collapsed below 5 pages")
        full = "\n".join((p.extract_text() or "") for p in reader.pages)
        for term in ("ApplyOS", "Prerequisites", "/setup", "JioStar", "Privacy warning",
                     "PowerShell", "Contents"):
            with self.subTest(term=term):
                self.assertIn(term, full)


if __name__ == "__main__":
    unittest.main()
